server:
  port: 19889
  servlet:
    context-path: /soros
spring:
  application:
    name: soros-data-adaptor
  jpa:
    properties:
      hibernate:
        ddl-auto: create-drop
#        ddl-auto: none
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5Dialect
        show_sql: false
  shardingsphere:
    datasource: #数据源配置
      names: rawdata
      common:
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
      rawdata:
        jdbc-url: jdbc:mysql://localhost:3306/rawdata?useSSL=false&serverTimezone=UTC
        username: root
        password: benmupen123
    rules:
      sharding:
        sharding-algorithms: #分片算法配置
          table-inline:
            type: MOD
            props:
              sharding-count: '100'
#            type: INLINE
#            props:
#              algorithm-expression: stock_history_$->{ st_code % 100 }

        key-generators: #主键生成策略
          snowflake:
            type: SNOWFLAKE
            props:
              worker-id: 1
        tables: #分表策略
          stock_history:
            actual-data-nodes: rawdata.stock_history_$->{0..99}
            table-strategy:
              standard:
                sharding-column: partition_code
                sharding-algorithm-name: table-inline
    props:
      sql-show: false
schedule:
  job:
    statisticsJobCron: 0 41 19,21,22 * * ?
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    hikari:
#      maximum-pool-size: 10
#      minimum-idle: 2
#      idle-timeout: 60000 # 1 MIN
#      max-lifetime: 600000 # 10 MIN
#    url: jdbc:mysql://localhost:3306/ai_learning?useSSL=false&serverTimezone=UTC
#    username: root
#    password: benmupen123

# 自定义异步任务线程池
async-task:
  # 核心线程池大小
  corePoolSize: 40
  # 最大线程数大小
  maximumPoolSize: 120
  # 活跃时间：秒
  keepAliveSeconds: 300
  # 线程等待队列大小
  queueCapacity: 3000
  # 自定义线程名称前缀
  threadNamePrefix: Async-Task-
  # 设置终止等待时间：秒
  awaitTerminationTime: 60
  # 线程结束前，是否等待线程队列中的任务执行完成
  waitTasksComplete: true

customer:
  config:
    startDate: 20100101
    historyHandleSize: 100
