server:
  port: 19889
  servlet:
    context-path: /soros
spring:
  application:
    name: soros-data-adaptor
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 60000 # 1 MIN
      max-lifetime: 600000 # 10 MIN
    url: jdbc:mysql://localhost:3306/ai_learning?useSSL=false&serverTimezone=UTC
    username: root
    password: benmupen123
